[web]
bind_address = "127.0.0.1:3030"
# external_address = "http://www.example.com"
backend = "in_memory"

[project_service]
list_limit = 20

[dataset_service]
list_limit = 20

[postgres]
config_string = "postgresql://geoengine:geoengine@localhost:5432"

[operators.gdal_source]
raster_data_root_path = "operators/test-data/raster"

[raster.tiling_specification]
origin_coordinate_x = 0.0
origin_coordinate_y = 0.0
tile_shape_pixels_x = 600
tile_shape_pixels_y = 600

[query_context]
chunk_byte_size = 1048576 # TODO: find reasonable default

[upload]
path = "upload"

[logging]
# Minimum log level. Can be one of error, warn, info, debug, trace
# or a more detailed spec. See https://docs.rs/flexi_logger/0.17.1/flexi_logger/struct.LogSpecification.html.
log_spec = "info"

# Whether the logs should be also written to files.
# Log files are rotated once per day. The last 7 files will be kept.
log_to_file = false

# Changes the first part of the log filename.
filename_prefix = "geo_engine"

# Buffer log output to improve performance in production.
enable_buffering = false

# By default logs are saved in the current working directory.
# Use this option if another folder should be used.
#log_directory = "/var/log/"
